Rename fields to messageFields
androiddevs-gr/slack-tools pull request #2
Opened 2017-04-24 07:14 UTC by pavlospt

2017-06-12 10:45 UTC, pavlospt commented
@alexstyl ping ☝️  :P

2017-06-14 10:50 UTC, alexstyl requested changes

2017-06-14 10:50 UTC, alexstyl commented on invite-to-slack/invite_to_slack.gs
>    if(lastResponse == null) return;
Can we extract the picking of the last response into a function so that it is easier to be read?

2017-06-14 10:52 UTC, pavlospt commented on invite-to-slack/invite_to_slack.gs
>    if(lastResponse == null) return;
@alexstyl No :P (kidding)

2017-06-14 13:50 UTC, pavlospt commented on invite-to-slack/invite_to_slack.gs
>    if(lastResponse == null) return;
@alexstyl done

2017-07-11 13:51 UTC, alexstyl approved these changes

2017-07-11 13:51 UTC, merged